### ISSUE TITLE
Post user-create causes a 500 error

### ISSUE THREAD

**Issue by AlexMakesSoftware** [ShivaniDattani/TMS_pro#6]
I log out.
I go to sign-up as a new user
Fill out of the form details
Then click 'signup'
I get a 500 error
Yet it does actually create the user and I can now log in.
Hmm....

**Comment by AlexMakesSoftware** [comment]
I know it's just a demo but we should probably add some proper logging to the system.

**Comment by ShivaniDattani** [comment]
Probably that is in production server, I have checked from my side and it is not giving me 500 error instead it is giving me 304.
[14/Nov/2023 15:01:33] "GET /static/enrollapp/css/style.css HTTP/1.1" 304 0: when I searched on internet, I found that the requested css/js files has not been changed since the last time it was requested and cached.

**Comment by AlexMakesSoftware** [comment]
Ah... I think I see the issue here. You're expecting a group (Staff-Group) to exist that doesn't get automatically added without manually doing it yourself.

From the logging I just added:

2023-11-17 17:56:30,067, ERROR, django.request, Internal Server Error: /signup/
Traceback (most recent call last):
  File "/var/www/projects/training_django/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/projects/training_django/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/projects/training_django/enrollapp/views.py", line 17, in sign_up
    group = Group.objects.get(name='Staff-Group')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/projects/training_django/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/projects/training_django/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

**Comment by AlexMakesSoftware** [comment]
Please can you have a think about what things (like groups) you need to be there by default and I'll work out how to automatically set them up on installation if they're not there.

Also, what permissions does 'Staff-Group' need?

**Comment by ShivaniDattani** [comment]
I did this because previously when user did sign up, they were not automatically checked is-active so they were not able to login, Instead Admin has to check they are active and then user can login. Now I have change the code and no need to put them in one group. Let see if it solves
